-- q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl.vhd

-- This file was auto-generated from altera_asmi_parallel2_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 17.1 590

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl is
	port (
		avl_csr_address         : in  std_logic_vector(5 downto 0)  := (others => '0'); --     avl_csr.address
		avl_csr_read            : in  std_logic                     := '0';             --            .read
		avl_csr_readdata        : out std_logic_vector(31 downto 0);                    --            .readdata
		avl_csr_write           : in  std_logic                     := '0';             --            .write
		avl_csr_writedata       : in  std_logic_vector(31 downto 0) := (others => '0'); --            .writedata
		avl_csr_waitrequest     : out std_logic;                                        --            .waitrequest
		avl_csr_readdatavalid   : out std_logic;                                        --            .readdatavalid
		avl_mem_address         : in  std_logic_vector(31 downto 0) := (others => '0'); --     avl_mem.address
		avl_mem_read            : in  std_logic                     := '0';             --            .read
		avl_mem_readdata        : out std_logic_vector(31 downto 0);                    --            .readdata
		avl_mem_write           : in  std_logic                     := '0';             --            .write
		avl_mem_writedata       : in  std_logic_vector(31 downto 0) := (others => '0'); --            .writedata
		avl_mem_byteenable      : in  std_logic_vector(3 downto 0)  := (others => '0'); --            .byteenable
		avl_mem_burstcount      : in  std_logic_vector(6 downto 0)  := (others => '0'); --            .burstcount
		avl_mem_waitrequest     : out std_logic;                                        --            .waitrequest
		avl_mem_readdatavalid   : out std_logic;                                        --            .readdatavalid
		clk_clk                 : in  std_logic                     := '0';             --         clk.clk
		reset_reset             : in  std_logic                     := '0';             --       reset.reset
		chip_select_chip_select : in  std_logic_vector(3 downto 0)  := (others => '0')  -- chip_select.chip_select
	);
end entity q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl;

architecture rtl of q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl is
	component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_csr_controller is
		port (
			csr_addr          : in  std_logic_vector(5 downto 0)  := (others => 'X'); -- address
			csr_rd            : in  std_logic                     := 'X';             -- read
			csr_rddata        : out std_logic_vector(31 downto 0);                    -- readdata
			csr_wr            : in  std_logic                     := 'X';             -- write
			csr_wrdata        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			csr_waitrequest   : out std_logic;                                        -- waitrequest
			csr_rddatavalid   : out std_logic;                                        -- readdatavalid
			clk               : in  std_logic                     := 'X';             -- clk
			reset             : in  std_logic                     := 'X';             -- reset
			cmd_channel       : out std_logic_vector(1 downto 0);                     -- channel
			cmd_eop           : out std_logic;                                        -- endofpacket
			cmd_ready         : in  std_logic                     := 'X';             -- ready
			cmd_sop           : out std_logic;                                        -- startofpacket
			cmd_data          : out std_logic_vector(31 downto 0);                    -- data
			cmd_valid         : out std_logic;                                        -- valid
			rsp_channel       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- channel
			rsp_data          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			rsp_eop           : in  std_logic                     := 'X';             -- endofpacket
			rsp_ready         : out std_logic;                                        -- ready
			rsp_sop           : in  std_logic                     := 'X';             -- startofpacket
			rsp_valid         : in  std_logic                     := 'X';             -- valid
			addr_bytes_csr    : out std_logic_vector(31 downto 0);                    -- addr_bytes_csr
			qspi_interface_en : out std_logic                                         -- qspi_interface_en
		);
	end component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_csr_controller;

	component altera_asmi2_xip_controller is
		generic (
			ADDR_WIDTH : integer := 32
		);
		port (
			clk             : in  std_logic                     := 'X';             -- clk
			reset           : in  std_logic                     := 'X';             -- reset
			mem_addr        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			mem_rd          : in  std_logic                     := 'X';             -- read
			mem_rddata      : out std_logic_vector(31 downto 0);                    -- readdata
			mem_wr          : in  std_logic                     := 'X';             -- write
			mem_wrdata      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			mem_byteenable  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			mem_burstcount  : in  std_logic_vector(6 downto 0)  := (others => 'X'); -- burstcount
			mem_waitrequest : out std_logic;                                        -- waitrequest
			mem_rddatavalid : out std_logic;                                        -- readdatavalid
			addr_bytes_xip  : out std_logic_vector(31 downto 0);                    -- addr_bytes_xip
			cmd_channel     : out std_logic_vector(1 downto 0);                     -- channel
			cmd_eop         : out std_logic;                                        -- endofpacket
			cmd_ready       : in  std_logic                     := 'X';             -- ready
			cmd_sop         : out std_logic;                                        -- startofpacket
			cmd_data        : out std_logic_vector(31 downto 0);                    -- data
			cmd_valid       : out std_logic;                                        -- valid
			rsp_channel     : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- channel
			rsp_data        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			rsp_eop         : in  std_logic                     := 'X';             -- endofpacket
			rsp_ready       : out std_logic;                                        -- ready
			rsp_sop         : in  std_logic                     := 'X';             -- startofpacket
			rsp_valid       : in  std_logic                     := 'X';             -- valid
			chip_select     : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- chip_select
		);
	end component altera_asmi2_xip_controller;

	component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_merlin_demultiplexer_0 is
		port (
			clk                : in  std_logic                     := 'X';             -- clk
			reset              : in  std_logic                     := 'X';             -- reset
			sink_ready         : out std_logic;                                        -- ready
			sink_channel       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- channel
			sink_data          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			sink_startofpacket : in  std_logic                     := 'X';             -- startofpacket
			sink_endofpacket   : in  std_logic                     := 'X';             -- endofpacket
			sink_valid         : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- valid
			src0_ready         : in  std_logic                     := 'X';             -- ready
			src0_valid         : out std_logic;                                        -- valid
			src0_data          : out std_logic_vector(31 downto 0);                    -- data
			src0_channel       : out std_logic_vector(1 downto 0);                     -- channel
			src0_startofpacket : out std_logic;                                        -- startofpacket
			src0_endofpacket   : out std_logic;                                        -- endofpacket
			src1_ready         : in  std_logic                     := 'X';             -- ready
			src1_valid         : out std_logic;                                        -- valid
			src1_data          : out std_logic_vector(31 downto 0);                    -- data
			src1_channel       : out std_logic_vector(1 downto 0);                     -- channel
			src1_startofpacket : out std_logic;                                        -- startofpacket
			src1_endofpacket   : out std_logic                                         -- endofpacket
		);
	end component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_merlin_demultiplexer_0;

	component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_multiplexer is
		port (
			clk                 : in  std_logic                     := 'X';             -- clk
			reset               : in  std_logic                     := 'X';             -- reset
			src_ready           : in  std_logic                     := 'X';             -- ready
			src_valid           : out std_logic;                                        -- valid
			src_data            : out std_logic_vector(31 downto 0);                    -- data
			src_channel         : out std_logic_vector(1 downto 0);                     -- channel
			src_startofpacket   : out std_logic;                                        -- startofpacket
			src_endofpacket     : out std_logic;                                        -- endofpacket
			sink0_ready         : out std_logic;                                        -- ready
			sink0_valid         : in  std_logic                     := 'X';             -- valid
			sink0_channel       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- channel
			sink0_data          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			sink0_startofpacket : in  std_logic                     := 'X';             -- startofpacket
			sink0_endofpacket   : in  std_logic                     := 'X';             -- endofpacket
			sink1_ready         : out std_logic;                                        -- ready
			sink1_valid         : in  std_logic                     := 'X';             -- valid
			sink1_channel       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- channel
			sink1_data          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			sink1_startofpacket : in  std_logic                     := 'X';             -- startofpacket
			sink1_endofpacket   : in  std_logic                     := 'X'              -- endofpacket
		);
	end component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_multiplexer;

	component altera_asmi2_cmd_generator is
		port (
			clk             : in  std_logic                     := 'X';             -- clk
			reset           : in  std_logic                     := 'X';             -- reset
			in_cmd_channel  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- channel
			in_cmd_eop      : in  std_logic                     := 'X';             -- endofpacket
			in_cmd_ready    : out std_logic;                                        -- ready
			in_cmd_sop      : in  std_logic                     := 'X';             -- startofpacket
			in_cmd_data     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			in_cmd_valid    : in  std_logic                     := 'X';             -- valid
			out_cmd_channel : out std_logic_vector(1 downto 0);                     -- channel
			out_cmd_eop     : out std_logic;                                        -- endofpacket
			out_cmd_ready   : in  std_logic                     := 'X';             -- ready
			out_cmd_sop     : out std_logic;                                        -- startofpacket
			out_cmd_data    : out std_logic_vector(7 downto 0);                     -- data
			out_cmd_valid   : out std_logic;                                        -- valid
			in_rsp_data     : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- data
			in_rsp_ready    : out std_logic;                                        -- ready
			in_rsp_valid    : in  std_logic                     := 'X';             -- valid
			out_rsp_channel : out std_logic_vector(1 downto 0);                     -- channel
			out_rsp_data    : out std_logic_vector(31 downto 0);                    -- data
			out_rsp_eop     : out std_logic;                                        -- endofpacket
			out_rsp_ready   : in  std_logic                     := 'X';             -- ready
			out_rsp_sop     : out std_logic;                                        -- startofpacket
			out_rsp_valid   : out std_logic;                                        -- valid
			addr_bytes_csr  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- addr_bytes_csr
			addr_bytes_xip  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- addr_bytes_xip
			dummy_cycles    : out std_logic_vector(4 downto 0);                     -- dummy_cycles
			chip_select     : out std_logic_vector(3 downto 0);                     -- chip_select
			require_rdata   : out std_logic                                         -- require_rdata
		);
	end component altera_asmi2_cmd_generator;

	component altera_asmi2_qspi_interface is
		generic (
			DEV_FAMILY       : string  := "Arria 10";
			NCS_LENGTH       : integer := 3;
			DATA_LENGTH      : integer := 4;
			MODE_LENGTH      : integer := 1;
			ENABLE_SIM_MODEL : string  := "false"
		);
		port (
			clk               : in  std_logic                    := 'X';             -- clk
			reset             : in  std_logic                    := 'X';             -- reset
			in_cmd_channel    : in  std_logic_vector(1 downto 0) := (others => 'X'); -- channel
			in_cmd_eop        : in  std_logic                    := 'X';             -- endofpacket
			in_cmd_ready      : out std_logic;                                       -- ready
			in_cmd_sop        : in  std_logic                    := 'X';             -- startofpacket
			in_cmd_data       : in  std_logic_vector(7 downto 0) := (others => 'X'); -- data
			in_cmd_valid      : in  std_logic                    := 'X';             -- valid
			out_rsp_data      : out std_logic_vector(7 downto 0);                    -- data
			out_rsp_valid     : out std_logic;                                       -- valid
			out_rsp_ready     : in  std_logic                    := 'X';             -- ready
			dummy_cycles      : in  std_logic_vector(4 downto 0) := (others => 'X'); -- dummy_cycles
			chip_select       : in  std_logic_vector(3 downto 0) := (others => 'X'); -- chip_select
			qspi_interface_en : in  std_logic                    := 'X';             -- qspi_interface_en
			require_rdata     : in  std_logic                    := 'X'              -- require_rdata
		);
	end component altera_asmi2_qspi_interface;

	component altera_reset_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller;

	signal csr_controller_cmd_pck_valid                       : std_logic;                     -- csr_controller:cmd_valid -> multiplexer:sink1_valid
	signal csr_controller_cmd_pck_data                        : std_logic_vector(31 downto 0); -- csr_controller:cmd_data -> multiplexer:sink1_data
	signal csr_controller_cmd_pck_ready                       : std_logic;                     -- multiplexer:sink1_ready -> csr_controller:cmd_ready
	signal csr_controller_cmd_pck_channel                     : std_logic_vector(1 downto 0);  -- csr_controller:cmd_channel -> multiplexer:sink1_channel
	signal csr_controller_cmd_pck_startofpacket               : std_logic;                     -- csr_controller:cmd_sop -> multiplexer:sink1_startofpacket
	signal csr_controller_cmd_pck_endofpacket                 : std_logic;                     -- csr_controller:cmd_eop -> multiplexer:sink1_endofpacket
	signal xip_controller_cmd_pck_valid                       : std_logic;                     -- xip_controller:cmd_valid -> multiplexer:sink0_valid
	signal xip_controller_cmd_pck_data                        : std_logic_vector(31 downto 0); -- xip_controller:cmd_data -> multiplexer:sink0_data
	signal xip_controller_cmd_pck_ready                       : std_logic;                     -- multiplexer:sink0_ready -> xip_controller:cmd_ready
	signal xip_controller_cmd_pck_channel                     : std_logic_vector(1 downto 0);  -- xip_controller:cmd_channel -> multiplexer:sink0_channel
	signal xip_controller_cmd_pck_startofpacket               : std_logic;                     -- xip_controller:cmd_sop -> multiplexer:sink0_startofpacket
	signal xip_controller_cmd_pck_endofpacket                 : std_logic;                     -- xip_controller:cmd_eop -> multiplexer:sink0_endofpacket
	signal merlin_demultiplexer_0_src1_valid                  : std_logic;                     -- merlin_demultiplexer_0:src1_valid -> csr_controller:rsp_valid
	signal merlin_demultiplexer_0_src1_data                   : std_logic_vector(31 downto 0); -- merlin_demultiplexer_0:src1_data -> csr_controller:rsp_data
	signal merlin_demultiplexer_0_src1_ready                  : std_logic;                     -- csr_controller:rsp_ready -> merlin_demultiplexer_0:src1_ready
	signal merlin_demultiplexer_0_src1_channel                : std_logic_vector(1 downto 0);  -- merlin_demultiplexer_0:src1_channel -> csr_controller:rsp_channel
	signal merlin_demultiplexer_0_src1_startofpacket          : std_logic;                     -- merlin_demultiplexer_0:src1_startofpacket -> csr_controller:rsp_sop
	signal merlin_demultiplexer_0_src1_endofpacket            : std_logic;                     -- merlin_demultiplexer_0:src1_endofpacket -> csr_controller:rsp_eop
	signal merlin_demultiplexer_0_src0_valid                  : std_logic;                     -- merlin_demultiplexer_0:src0_valid -> xip_controller:rsp_valid
	signal merlin_demultiplexer_0_src0_data                   : std_logic_vector(31 downto 0); -- merlin_demultiplexer_0:src0_data -> xip_controller:rsp_data
	signal merlin_demultiplexer_0_src0_ready                  : std_logic;                     -- xip_controller:rsp_ready -> merlin_demultiplexer_0:src0_ready
	signal merlin_demultiplexer_0_src0_channel                : std_logic_vector(1 downto 0);  -- merlin_demultiplexer_0:src0_channel -> xip_controller:rsp_channel
	signal merlin_demultiplexer_0_src0_startofpacket          : std_logic;                     -- merlin_demultiplexer_0:src0_startofpacket -> xip_controller:rsp_sop
	signal merlin_demultiplexer_0_src0_endofpacket            : std_logic;                     -- merlin_demultiplexer_0:src0_endofpacket -> xip_controller:rsp_eop
	signal csr_controller_addr_bytes_csr_addr_bytes_csr       : std_logic_vector(31 downto 0); -- csr_controller:addr_bytes_csr -> asmi2_cmd_generator_0:addr_bytes_csr
	signal xip_controller_addr_bytes_xip_addr_bytes_xip       : std_logic_vector(31 downto 0); -- xip_controller:addr_bytes_xip -> asmi2_cmd_generator_0:addr_bytes_xip
	signal asmi2_cmd_generator_0_out_rsp_pck_valid            : std_logic;                     -- asmi2_cmd_generator_0:out_rsp_valid -> merlin_demultiplexer_0:sink_valid
	signal asmi2_cmd_generator_0_out_rsp_pck_data             : std_logic_vector(31 downto 0); -- asmi2_cmd_generator_0:out_rsp_data -> merlin_demultiplexer_0:sink_data
	signal asmi2_cmd_generator_0_out_rsp_pck_ready            : std_logic;                     -- merlin_demultiplexer_0:sink_ready -> asmi2_cmd_generator_0:out_rsp_ready
	signal asmi2_cmd_generator_0_out_rsp_pck_channel          : std_logic_vector(1 downto 0);  -- asmi2_cmd_generator_0:out_rsp_channel -> merlin_demultiplexer_0:sink_channel
	signal asmi2_cmd_generator_0_out_rsp_pck_startofpacket    : std_logic;                     -- asmi2_cmd_generator_0:out_rsp_sop -> merlin_demultiplexer_0:sink_startofpacket
	signal asmi2_cmd_generator_0_out_rsp_pck_endofpacket      : std_logic;                     -- asmi2_cmd_generator_0:out_rsp_eop -> merlin_demultiplexer_0:sink_endofpacket
	signal asmi2_qspi_interface_0_out_rsp_pck_valid           : std_logic;                     -- asmi2_qspi_interface_0:out_rsp_valid -> asmi2_cmd_generator_0:in_rsp_valid
	signal asmi2_qspi_interface_0_out_rsp_pck_data            : std_logic_vector(7 downto 0);  -- asmi2_qspi_interface_0:out_rsp_data -> asmi2_cmd_generator_0:in_rsp_data
	signal asmi2_qspi_interface_0_out_rsp_pck_ready           : std_logic;                     -- asmi2_cmd_generator_0:in_rsp_ready -> asmi2_qspi_interface_0:out_rsp_ready
	signal asmi2_cmd_generator_0_dummy_cycles_dummy_cycles    : std_logic_vector(4 downto 0);  -- asmi2_cmd_generator_0:dummy_cycles -> asmi2_qspi_interface_0:dummy_cycles
	signal asmi2_cmd_generator_0_chip_select_chip_select      : std_logic_vector(3 downto 0);  -- asmi2_cmd_generator_0:chip_select -> asmi2_qspi_interface_0:chip_select
	signal asmi2_cmd_generator_0_require_rdata_require_rdata  : std_logic;                     -- asmi2_cmd_generator_0:require_rdata -> asmi2_qspi_interface_0:require_rdata
	signal csr_controller_qspi_interface_en_qspi_interface_en : std_logic;                     -- csr_controller:qspi_interface_en -> asmi2_qspi_interface_0:qspi_interface_en
	signal asmi2_cmd_generator_0_out_cmd_pck_valid            : std_logic;                     -- asmi2_cmd_generator_0:out_cmd_valid -> asmi2_qspi_interface_0:in_cmd_valid
	signal asmi2_cmd_generator_0_out_cmd_pck_data             : std_logic_vector(7 downto 0);  -- asmi2_cmd_generator_0:out_cmd_data -> asmi2_qspi_interface_0:in_cmd_data
	signal asmi2_cmd_generator_0_out_cmd_pck_ready            : std_logic;                     -- asmi2_qspi_interface_0:in_cmd_ready -> asmi2_cmd_generator_0:out_cmd_ready
	signal asmi2_cmd_generator_0_out_cmd_pck_channel          : std_logic_vector(1 downto 0);  -- asmi2_cmd_generator_0:out_cmd_channel -> asmi2_qspi_interface_0:in_cmd_channel
	signal asmi2_cmd_generator_0_out_cmd_pck_startofpacket    : std_logic;                     -- asmi2_cmd_generator_0:out_cmd_sop -> asmi2_qspi_interface_0:in_cmd_sop
	signal asmi2_cmd_generator_0_out_cmd_pck_endofpacket      : std_logic;                     -- asmi2_cmd_generator_0:out_cmd_eop -> asmi2_qspi_interface_0:in_cmd_eop
	signal multiplexer_src_valid                              : std_logic;                     -- multiplexer:src_valid -> asmi2_cmd_generator_0:in_cmd_valid
	signal multiplexer_src_data                               : std_logic_vector(31 downto 0); -- multiplexer:src_data -> asmi2_cmd_generator_0:in_cmd_data
	signal multiplexer_src_ready                              : std_logic;                     -- asmi2_cmd_generator_0:in_cmd_ready -> multiplexer:src_ready
	signal multiplexer_src_channel                            : std_logic_vector(1 downto 0);  -- multiplexer:src_channel -> asmi2_cmd_generator_0:in_cmd_channel
	signal multiplexer_src_startofpacket                      : std_logic;                     -- multiplexer:src_startofpacket -> asmi2_cmd_generator_0:in_cmd_sop
	signal multiplexer_src_endofpacket                        : std_logic;                     -- multiplexer:src_endofpacket -> asmi2_cmd_generator_0:in_cmd_eop
	signal rst_controller_reset_out_reset                     : std_logic;                     -- rst_controller:reset_out -> [asmi2_cmd_generator_0:reset, asmi2_qspi_interface_0:reset, csr_controller:reset, merlin_demultiplexer_0:reset, multiplexer:reset, xip_controller:reset]

begin

	csr_controller : component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_csr_controller
		port map (
			csr_addr          => avl_csr_address,                                    --               csr.address
			csr_rd            => avl_csr_read,                                       --                  .read
			csr_rddata        => avl_csr_readdata,                                   --                  .readdata
			csr_wr            => avl_csr_write,                                      --                  .write
			csr_wrdata        => avl_csr_writedata,                                  --                  .writedata
			csr_waitrequest   => avl_csr_waitrequest,                                --                  .waitrequest
			csr_rddatavalid   => avl_csr_readdatavalid,                              --                  .readdatavalid
			clk               => clk_clk,                                            --               clk.clk
			reset             => rst_controller_reset_out_reset,                     --             reset.reset
			cmd_channel       => csr_controller_cmd_pck_channel,                     --           cmd_pck.channel
			cmd_eop           => csr_controller_cmd_pck_endofpacket,                 --                  .endofpacket
			cmd_ready         => csr_controller_cmd_pck_ready,                       --                  .ready
			cmd_sop           => csr_controller_cmd_pck_startofpacket,               --                  .startofpacket
			cmd_data          => csr_controller_cmd_pck_data,                        --                  .data
			cmd_valid         => csr_controller_cmd_pck_valid,                       --                  .valid
			rsp_channel       => merlin_demultiplexer_0_src1_channel,                --           rsp_pck.channel
			rsp_data          => merlin_demultiplexer_0_src1_data,                   --                  .data
			rsp_eop           => merlin_demultiplexer_0_src1_endofpacket,            --                  .endofpacket
			rsp_ready         => merlin_demultiplexer_0_src1_ready,                  --                  .ready
			rsp_sop           => merlin_demultiplexer_0_src1_startofpacket,          --                  .startofpacket
			rsp_valid         => merlin_demultiplexer_0_src1_valid,                  --                  .valid
			addr_bytes_csr    => csr_controller_addr_bytes_csr_addr_bytes_csr,       --    addr_bytes_csr.addr_bytes_csr
			qspi_interface_en => csr_controller_qspi_interface_en_qspi_interface_en  -- qspi_interface_en.qspi_interface_en
		);

	xip_controller : component altera_asmi2_xip_controller
		generic map (
			ADDR_WIDTH => 32
		)
		port map (
			clk             => clk_clk,                                      --            clk.clk
			reset           => rst_controller_reset_out_reset,               --          reset.reset
			mem_addr        => avl_mem_address,                              --            mem.address
			mem_rd          => avl_mem_read,                                 --               .read
			mem_rddata      => avl_mem_readdata,                             --               .readdata
			mem_wr          => avl_mem_write,                                --               .write
			mem_wrdata      => avl_mem_writedata,                            --               .writedata
			mem_byteenable  => avl_mem_byteenable,                           --               .byteenable
			mem_burstcount  => avl_mem_burstcount,                           --               .burstcount
			mem_waitrequest => avl_mem_waitrequest,                          --               .waitrequest
			mem_rddatavalid => avl_mem_readdatavalid,                        --               .readdatavalid
			addr_bytes_xip  => xip_controller_addr_bytes_xip_addr_bytes_xip, -- addr_bytes_xip.addr_bytes_xip
			cmd_channel     => xip_controller_cmd_pck_channel,               --        cmd_pck.channel
			cmd_eop         => xip_controller_cmd_pck_endofpacket,           --               .endofpacket
			cmd_ready       => xip_controller_cmd_pck_ready,                 --               .ready
			cmd_sop         => xip_controller_cmd_pck_startofpacket,         --               .startofpacket
			cmd_data        => xip_controller_cmd_pck_data,                  --               .data
			cmd_valid       => xip_controller_cmd_pck_valid,                 --               .valid
			rsp_channel     => merlin_demultiplexer_0_src0_channel,          --        rsp_pck.channel
			rsp_data        => merlin_demultiplexer_0_src0_data,             --               .data
			rsp_eop         => merlin_demultiplexer_0_src0_endofpacket,      --               .endofpacket
			rsp_ready       => merlin_demultiplexer_0_src0_ready,            --               .ready
			rsp_sop         => merlin_demultiplexer_0_src0_startofpacket,    --               .startofpacket
			rsp_valid       => merlin_demultiplexer_0_src0_valid,            --               .valid
			chip_select     => chip_select_chip_select                       --    chip_select.chip_select
		);

	merlin_demultiplexer_0 : component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_merlin_demultiplexer_0
		port map (
			clk                => clk_clk,                                         --       clk.clk
			reset              => rst_controller_reset_out_reset,                  -- clk_reset.reset
			sink_ready         => asmi2_cmd_generator_0_out_rsp_pck_ready,         --      sink.ready
			sink_channel       => asmi2_cmd_generator_0_out_rsp_pck_channel,       --          .channel
			sink_data          => asmi2_cmd_generator_0_out_rsp_pck_data,          --          .data
			sink_startofpacket => asmi2_cmd_generator_0_out_rsp_pck_startofpacket, --          .startofpacket
			sink_endofpacket   => asmi2_cmd_generator_0_out_rsp_pck_endofpacket,   --          .endofpacket
			sink_valid(0)      => asmi2_cmd_generator_0_out_rsp_pck_valid,         --          .valid
			src0_ready         => merlin_demultiplexer_0_src0_ready,               --      src0.ready
			src0_valid         => merlin_demultiplexer_0_src0_valid,               --          .valid
			src0_data          => merlin_demultiplexer_0_src0_data,                --          .data
			src0_channel       => merlin_demultiplexer_0_src0_channel,             --          .channel
			src0_startofpacket => merlin_demultiplexer_0_src0_startofpacket,       --          .startofpacket
			src0_endofpacket   => merlin_demultiplexer_0_src0_endofpacket,         --          .endofpacket
			src1_ready         => merlin_demultiplexer_0_src1_ready,               --      src1.ready
			src1_valid         => merlin_demultiplexer_0_src1_valid,               --          .valid
			src1_data          => merlin_demultiplexer_0_src1_data,                --          .data
			src1_channel       => merlin_demultiplexer_0_src1_channel,             --          .channel
			src1_startofpacket => merlin_demultiplexer_0_src1_startofpacket,       --          .startofpacket
			src1_endofpacket   => merlin_demultiplexer_0_src1_endofpacket          --          .endofpacket
		);

	multiplexer : component q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl_multiplexer
		port map (
			clk                 => clk_clk,                              --       clk.clk
			reset               => rst_controller_reset_out_reset,       -- clk_reset.reset
			src_ready           => multiplexer_src_ready,                --       src.ready
			src_valid           => multiplexer_src_valid,                --          .valid
			src_data            => multiplexer_src_data,                 --          .data
			src_channel         => multiplexer_src_channel,              --          .channel
			src_startofpacket   => multiplexer_src_startofpacket,        --          .startofpacket
			src_endofpacket     => multiplexer_src_endofpacket,          --          .endofpacket
			sink0_ready         => xip_controller_cmd_pck_ready,         --     sink0.ready
			sink0_valid         => xip_controller_cmd_pck_valid,         --          .valid
			sink0_channel       => xip_controller_cmd_pck_channel,       --          .channel
			sink0_data          => xip_controller_cmd_pck_data,          --          .data
			sink0_startofpacket => xip_controller_cmd_pck_startofpacket, --          .startofpacket
			sink0_endofpacket   => xip_controller_cmd_pck_endofpacket,   --          .endofpacket
			sink1_ready         => csr_controller_cmd_pck_ready,         --     sink1.ready
			sink1_valid         => csr_controller_cmd_pck_valid,         --          .valid
			sink1_channel       => csr_controller_cmd_pck_channel,       --          .channel
			sink1_data          => csr_controller_cmd_pck_data,          --          .data
			sink1_startofpacket => csr_controller_cmd_pck_startofpacket, --          .startofpacket
			sink1_endofpacket   => csr_controller_cmd_pck_endofpacket    --          .endofpacket
		);

	asmi2_cmd_generator_0 : component altera_asmi2_cmd_generator
		port map (
			clk             => clk_clk,                                           --            clk.clk
			reset           => rst_controller_reset_out_reset,                    --          reset.reset
			in_cmd_channel  => multiplexer_src_channel,                           --     in_cmd_pck.channel
			in_cmd_eop      => multiplexer_src_endofpacket,                       --               .endofpacket
			in_cmd_ready    => multiplexer_src_ready,                             --               .ready
			in_cmd_sop      => multiplexer_src_startofpacket,                     --               .startofpacket
			in_cmd_data     => multiplexer_src_data,                              --               .data
			in_cmd_valid    => multiplexer_src_valid,                             --               .valid
			out_cmd_channel => asmi2_cmd_generator_0_out_cmd_pck_channel,         --    out_cmd_pck.channel
			out_cmd_eop     => asmi2_cmd_generator_0_out_cmd_pck_endofpacket,     --               .endofpacket
			out_cmd_ready   => asmi2_cmd_generator_0_out_cmd_pck_ready,           --               .ready
			out_cmd_sop     => asmi2_cmd_generator_0_out_cmd_pck_startofpacket,   --               .startofpacket
			out_cmd_data    => asmi2_cmd_generator_0_out_cmd_pck_data,            --               .data
			out_cmd_valid   => asmi2_cmd_generator_0_out_cmd_pck_valid,           --               .valid
			in_rsp_data     => asmi2_qspi_interface_0_out_rsp_pck_data,           --     in_rsp_pck.data
			in_rsp_ready    => asmi2_qspi_interface_0_out_rsp_pck_ready,          --               .ready
			in_rsp_valid    => asmi2_qspi_interface_0_out_rsp_pck_valid,          --               .valid
			out_rsp_channel => asmi2_cmd_generator_0_out_rsp_pck_channel,         --    out_rsp_pck.channel
			out_rsp_data    => asmi2_cmd_generator_0_out_rsp_pck_data,            --               .data
			out_rsp_eop     => asmi2_cmd_generator_0_out_rsp_pck_endofpacket,     --               .endofpacket
			out_rsp_ready   => asmi2_cmd_generator_0_out_rsp_pck_ready,           --               .ready
			out_rsp_sop     => asmi2_cmd_generator_0_out_rsp_pck_startofpacket,   --               .startofpacket
			out_rsp_valid   => asmi2_cmd_generator_0_out_rsp_pck_valid,           --               .valid
			addr_bytes_csr  => csr_controller_addr_bytes_csr_addr_bytes_csr,      -- addr_bytes_csr.addr_bytes_csr
			addr_bytes_xip  => xip_controller_addr_bytes_xip_addr_bytes_xip,      -- addr_bytes_xip.addr_bytes_xip
			dummy_cycles    => asmi2_cmd_generator_0_dummy_cycles_dummy_cycles,   --   dummy_cycles.dummy_cycles
			chip_select     => asmi2_cmd_generator_0_chip_select_chip_select,     --    chip_select.chip_select
			require_rdata   => asmi2_cmd_generator_0_require_rdata_require_rdata  --  require_rdata.require_rdata
		);

	asmi2_qspi_interface_0 : component altera_asmi2_qspi_interface
		generic map (
			DEV_FAMILY       => "Cyclone 10 LP",
			NCS_LENGTH       => 1,
			DATA_LENGTH      => 2,
			MODE_LENGTH      => 1,
			ENABLE_SIM_MODEL => "false"
		)
		port map (
			clk               => clk_clk,                                            --               clk.clk
			reset             => rst_controller_reset_out_reset,                     --             reset.reset
			in_cmd_channel    => asmi2_cmd_generator_0_out_cmd_pck_channel,          --        in_cmd_pck.channel
			in_cmd_eop        => asmi2_cmd_generator_0_out_cmd_pck_endofpacket,      --                  .endofpacket
			in_cmd_ready      => asmi2_cmd_generator_0_out_cmd_pck_ready,            --                  .ready
			in_cmd_sop        => asmi2_cmd_generator_0_out_cmd_pck_startofpacket,    --                  .startofpacket
			in_cmd_data       => asmi2_cmd_generator_0_out_cmd_pck_data,             --                  .data
			in_cmd_valid      => asmi2_cmd_generator_0_out_cmd_pck_valid,            --                  .valid
			out_rsp_data      => asmi2_qspi_interface_0_out_rsp_pck_data,            --       out_rsp_pck.data
			out_rsp_valid     => asmi2_qspi_interface_0_out_rsp_pck_valid,           --                  .valid
			out_rsp_ready     => asmi2_qspi_interface_0_out_rsp_pck_ready,           --                  .ready
			dummy_cycles      => asmi2_cmd_generator_0_dummy_cycles_dummy_cycles,    --      dummy_cycles.dummy_cycles
			chip_select       => asmi2_cmd_generator_0_chip_select_chip_select,      --       chip_select.chip_select
			qspi_interface_en => csr_controller_qspi_interface_en_qspi_interface_en, -- qspi_interface_en.qspi_interface_en
			require_rdata     => asmi2_cmd_generator_0_require_rdata_require_rdata   --     require_rdata.require_rdata
		);

	rst_controller : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset,                    -- reset_in0.reset
			clk            => clk_clk,                        --       clk.clk
			reset_out      => rst_controller_reset_out_reset, -- reset_out.reset
			reset_req      => open,                           -- (terminated)
			reset_req_in0  => '0',                            -- (terminated)
			reset_in1      => '0',                            -- (terminated)
			reset_req_in1  => '0',                            -- (terminated)
			reset_in2      => '0',                            -- (terminated)
			reset_req_in2  => '0',                            -- (terminated)
			reset_in3      => '0',                            -- (terminated)
			reset_req_in3  => '0',                            -- (terminated)
			reset_in4      => '0',                            -- (terminated)
			reset_req_in4  => '0',                            -- (terminated)
			reset_in5      => '0',                            -- (terminated)
			reset_req_in5  => '0',                            -- (terminated)
			reset_in6      => '0',                            -- (terminated)
			reset_req_in6  => '0',                            -- (terminated)
			reset_in7      => '0',                            -- (terminated)
			reset_req_in7  => '0',                            -- (terminated)
			reset_in8      => '0',                            -- (terminated)
			reset_req_in8  => '0',                            -- (terminated)
			reset_in9      => '0',                            -- (terminated)
			reset_req_in9  => '0',                            -- (terminated)
			reset_in10     => '0',                            -- (terminated)
			reset_req_in10 => '0',                            -- (terminated)
			reset_in11     => '0',                            -- (terminated)
			reset_req_in11 => '0',                            -- (terminated)
			reset_in12     => '0',                            -- (terminated)
			reset_req_in12 => '0',                            -- (terminated)
			reset_in13     => '0',                            -- (terminated)
			reset_req_in13 => '0',                            -- (terminated)
			reset_in14     => '0',                            -- (terminated)
			reset_req_in14 => '0',                            -- (terminated)
			reset_in15     => '0',                            -- (terminated)
			reset_req_in15 => '0'                             -- (terminated)
		);

end architecture rtl; -- of q_sys_ext_epcq_flash_asmi2_inst_epcq_ctrl
