-- q_sys_msgdma_rx.vhd

-- This file was auto-generated from altera_msgdma_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 18.1 625

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity q_sys_msgdma_rx is
	port (
		mm_write_address                           : out std_logic_vector(26 downto 0);                    --                mm_write.address
		mm_write_write                             : out std_logic;                                        --                        .write
		mm_write_byteenable                        : out std_logic_vector(3 downto 0);                     --                        .byteenable
		mm_write_writedata                         : out std_logic_vector(31 downto 0);                    --                        .writedata
		mm_write_waitrequest                       : in  std_logic                     := '0';             --                        .waitrequest
		descriptor_read_master_address             : out std_logic_vector(14 downto 0);                    --  descriptor_read_master.address
		descriptor_read_master_read                : out std_logic;                                        --                        .read
		descriptor_read_master_readdata            : in  std_logic_vector(31 downto 0) := (others => '0'); --                        .readdata
		descriptor_read_master_waitrequest         : in  std_logic                     := '0';             --                        .waitrequest
		descriptor_read_master_readdatavalid       : in  std_logic                     := '0';             --                        .readdatavalid
		descriptor_write_master_address            : out std_logic_vector(14 downto 0);                    -- descriptor_write_master.address
		descriptor_write_master_write              : out std_logic;                                        --                        .write
		descriptor_write_master_byteenable         : out std_logic_vector(3 downto 0);                     --                        .byteenable
		descriptor_write_master_writedata          : out std_logic_vector(31 downto 0);                    --                        .writedata
		descriptor_write_master_waitrequest        : in  std_logic                     := '0';             --                        .waitrequest
		descriptor_write_master_response           : in  std_logic_vector(1 downto 0)  := (others => '0'); --                        .response
		descriptor_write_master_writeresponsevalid : in  std_logic                     := '0';             --                        .writeresponsevalid
		clock_clk                                  : in  std_logic                     := '0';             --                   clock.clk
		reset_n_reset_n                            : in  std_logic                     := '0';             --                 reset_n.reset_n
		csr_writedata                              : in  std_logic_vector(31 downto 0) := (others => '0'); --                     csr.writedata
		csr_write                                  : in  std_logic                     := '0';             --                        .write
		csr_byteenable                             : in  std_logic_vector(3 downto 0)  := (others => '0'); --                        .byteenable
		csr_readdata                               : out std_logic_vector(31 downto 0);                    --                        .readdata
		csr_read                                   : in  std_logic                     := '0';             --                        .read
		csr_address                                : in  std_logic_vector(2 downto 0)  := (others => '0'); --                        .address
		prefetcher_csr_address                     : in  std_logic_vector(2 downto 0)  := (others => '0'); --          prefetcher_csr.address
		prefetcher_csr_read                        : in  std_logic                     := '0';             --                        .read
		prefetcher_csr_write                       : in  std_logic                     := '0';             --                        .write
		prefetcher_csr_writedata                   : in  std_logic_vector(31 downto 0) := (others => '0'); --                        .writedata
		prefetcher_csr_readdata                    : out std_logic_vector(31 downto 0);                    --                        .readdata
		csr_irq_irq                                : out std_logic;                                        --                 csr_irq.irq
		st_sink_data                               : in  std_logic_vector(31 downto 0) := (others => '0'); --                 st_sink.data
		st_sink_valid                              : in  std_logic                     := '0';             --                        .valid
		st_sink_ready                              : out std_logic;                                        --                        .ready
		st_sink_startofpacket                      : in  std_logic                     := '0';             --                        .startofpacket
		st_sink_endofpacket                        : in  std_logic                     := '0';             --                        .endofpacket
		st_sink_empty                              : in  std_logic_vector(1 downto 0)  := (others => '0'); --                        .empty
		st_sink_error                              : in  std_logic_vector(5 downto 0)  := (others => '0')  --                        .error
	);
end entity q_sys_msgdma_rx;

architecture rtl of q_sys_msgdma_rx is
	component dispatcher is
		generic (
			MODE                        : integer := 0;
			RESPONSE_PORT               : integer := 0;
			DESCRIPTOR_INTERFACE        : integer := 0;
			DESCRIPTOR_FIFO_DEPTH       : integer := 128;
			ENHANCED_FEATURES           : integer := 1;
			DESCRIPTOR_WIDTH            : integer := 256;
			DESCRIPTOR_BYTEENABLE_WIDTH : integer := 32
		);
		port (
			clk                     : in  std_logic                      := 'X';             -- clk
			reset                   : in  std_logic                      := 'X';             -- reset
			csr_writedata           : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- writedata
			csr_write               : in  std_logic                      := 'X';             -- write
			csr_byteenable          : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			csr_readdata            : out std_logic_vector(31 downto 0);                     -- readdata
			csr_read                : in  std_logic                      := 'X';             -- read
			csr_address             : in  std_logic_vector(2 downto 0)   := (others => 'X'); -- address
			src_response_data       : out std_logic_vector(255 downto 0);                    -- data
			src_response_valid      : out std_logic;                                         -- valid
			src_response_ready      : in  std_logic                      := 'X';             -- ready
			snk_descriptor_data     : in  std_logic_vector(127 downto 0) := (others => 'X'); -- data
			snk_descriptor_valid    : in  std_logic                      := 'X';             -- valid
			snk_descriptor_ready    : out std_logic;                                         -- ready
			src_write_master_data   : out std_logic_vector(255 downto 0);                    -- data
			src_write_master_valid  : out std_logic;                                         -- valid
			src_write_master_ready  : in  std_logic                      := 'X';             -- ready
			snk_write_master_data   : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_write_master_valid  : in  std_logic                      := 'X';             -- valid
			snk_write_master_ready  : out std_logic;                                         -- ready
			descriptor_write        : in  std_logic                      := 'X';             -- write
			descriptor_waitrequest  : out std_logic;                                         -- waitrequest
			descriptor_writedata    : in  std_logic_vector(127 downto 0) := (others => 'X'); -- writedata
			descriptor_byteenable   : in  std_logic_vector(15 downto 0)  := (others => 'X'); -- byteenable
			mm_response_waitrequest : out std_logic;                                         -- waitrequest
			mm_response_byteenable  : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			mm_response_address     : in  std_logic                      := 'X';             -- address
			mm_response_readdata    : out std_logic_vector(31 downto 0);                     -- readdata
			mm_response_read        : in  std_logic                      := 'X';             -- read
			src_read_master_data    : out std_logic_vector(255 downto 0);                    -- data
			src_read_master_valid   : out std_logic;                                         -- valid
			src_read_master_ready   : in  std_logic                      := 'X';             -- ready
			snk_read_master_data    : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_read_master_valid   : in  std_logic                      := 'X';             -- valid
			snk_read_master_ready   : out std_logic;                                         -- ready
			csr_irq                 : out std_logic                                          -- irq
		);
	end component dispatcher;

	component altera_msgdma_prefetcher is
		generic (
			ENHANCED_FEATURES          : integer := 0;
			ENABLE_READ_BURST          : integer := 0;
			MAX_READ_BURST_COUNT       : integer := 2;
			MAX_READ_BURST_COUNT_WIDTH : integer := 2;
			DATA_WIDTH                 : integer := 32;
			DATA_BYTEENABLE_WIDTH      : integer := 4;
			DESCRIPTOR_WIDTH           : integer := 128;
			ADDRESS_WIDTH              : integer := 32;
			RESPONSE_FIFO_DEPTH        : integer := 32;
			RESPONSE_FIFO_DEPTH_LOG2   : integer := 5
		);
		port (
			clk                         : in  std_logic                      := 'X';             -- clk
			reset                       : in  std_logic                      := 'X';             -- reset
			mm_read_address             : out std_logic_vector(14 downto 0);                     -- address
			mm_read_read                : out std_logic;                                         -- read
			mm_read_readdata            : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- readdata
			mm_read_waitrequest         : in  std_logic                      := 'X';             -- waitrequest
			mm_read_readdatavalid       : in  std_logic                      := 'X';             -- readdatavalid
			mm_write_address            : out std_logic_vector(14 downto 0);                     -- address
			mm_write_write              : out std_logic;                                         -- write
			mm_write_byteenable         : out std_logic_vector(3 downto 0);                      -- byteenable
			mm_write_writedata          : out std_logic_vector(31 downto 0);                     -- writedata
			mm_write_waitrequest        : in  std_logic                      := 'X';             -- waitrequest
			mm_write_response           : in  std_logic_vector(1 downto 0)   := (others => 'X'); -- response
			mm_write_writeresponsevalid : in  std_logic                      := 'X';             -- writeresponsevalid
			st_src_descr_data           : out std_logic_vector(127 downto 0);                    -- data
			st_src_descr_valid          : out std_logic;                                         -- valid
			st_src_descr_ready          : in  std_logic                      := 'X';             -- ready
			st_snk_data                 : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			st_snk_valid                : in  std_logic                      := 'X';             -- valid
			st_snk_ready                : out std_logic;                                         -- ready
			mm_csr_address              : in  std_logic_vector(2 downto 0)   := (others => 'X'); -- address
			mm_csr_read                 : in  std_logic                      := 'X';             -- read
			mm_csr_write                : in  std_logic                      := 'X';             -- write
			mm_csr_writedata            : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- writedata
			mm_csr_readdata             : out std_logic_vector(31 downto 0);                     -- readdata
			csr_irq                     : out std_logic;                                         -- irq
			mm_read_burstcount          : out std_logic_vector(0 downto 0)                       -- burstcount
		);
	end component altera_msgdma_prefetcher;

	component write_master is
		generic (
			DATA_WIDTH                     : integer := 32;
			LENGTH_WIDTH                   : integer := 32;
			FIFO_DEPTH                     : integer := 32;
			STRIDE_ENABLE                  : integer := 0;
			BURST_ENABLE                   : integer := 0;
			PACKET_ENABLE                  : integer := 0;
			ERROR_ENABLE                   : integer := 0;
			ERROR_WIDTH                    : integer := 8;
			BYTE_ENABLE_WIDTH              : integer := 4;
			BYTE_ENABLE_WIDTH_LOG2         : integer := 2;
			ADDRESS_WIDTH                  : integer := 32;
			FIFO_DEPTH_LOG2                : integer := 5;
			SYMBOL_WIDTH                   : integer := 8;
			NUMBER_OF_SYMBOLS              : integer := 4;
			NUMBER_OF_SYMBOLS_LOG2         : integer := 2;
			MAX_BURST_COUNT_WIDTH          : integer := 2;
			UNALIGNED_ACCESSES_ENABLE      : integer := 0;
			ONLY_FULL_ACCESS_ENABLE        : integer := 0;
			BURST_WRAPPING_SUPPORT         : integer := 1;
			PROGRAMMABLE_BURST_ENABLE      : integer := 0;
			MAX_BURST_COUNT                : integer := 2;
			FIFO_SPEED_OPTIMIZATION        : integer := 1;
			STRIDE_WIDTH                   : integer := 1;
			ACTUAL_BYTES_TRANSFERRED_WIDTH : integer := 32
		);
		port (
			clk                : in  std_logic                      := 'X';             -- clk
			reset              : in  std_logic                      := 'X';             -- reset
			master_address     : out std_logic_vector(26 downto 0);                     -- address
			master_write       : out std_logic;                                         -- write
			master_byteenable  : out std_logic_vector(3 downto 0);                      -- byteenable
			master_writedata   : out std_logic_vector(31 downto 0);                     -- writedata
			master_waitrequest : in  std_logic                      := 'X';             -- waitrequest
			snk_data           : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- data
			snk_valid          : in  std_logic                      := 'X';             -- valid
			snk_ready          : out std_logic;                                         -- ready
			snk_sop            : in  std_logic                      := 'X';             -- startofpacket
			snk_eop            : in  std_logic                      := 'X';             -- endofpacket
			snk_empty          : in  std_logic_vector(1 downto 0)   := (others => 'X'); -- empty
			snk_error          : in  std_logic_vector(5 downto 0)   := (others => 'X'); -- error
			snk_command_data   : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_command_valid  : in  std_logic                      := 'X';             -- valid
			snk_command_ready  : out std_logic;                                         -- ready
			src_response_data  : out std_logic_vector(255 downto 0);                    -- data
			src_response_valid : out std_logic;                                         -- valid
			src_response_ready : in  std_logic                      := 'X';             -- ready
			master_burstcount  : out std_logic_vector(0 downto 0)                       -- burstcount
		);
	end component write_master;

	signal prefetcher_internal_descriptor_write_dispatcher_source_valid : std_logic;                      -- prefetcher_internal:st_src_descr_valid -> dispatcher_internal:snk_descriptor_valid
	signal prefetcher_internal_descriptor_write_dispatcher_source_data  : std_logic_vector(127 downto 0); -- prefetcher_internal:st_src_descr_data -> dispatcher_internal:snk_descriptor_data
	signal prefetcher_internal_descriptor_write_dispatcher_source_ready : std_logic;                      -- dispatcher_internal:snk_descriptor_ready -> prefetcher_internal:st_src_descr_ready
	signal dispatcher_internal_response_source_valid                    : std_logic;                      -- dispatcher_internal:src_response_valid -> prefetcher_internal:st_snk_valid
	signal dispatcher_internal_response_source_data                     : std_logic_vector(255 downto 0); -- dispatcher_internal:src_response_data -> prefetcher_internal:st_snk_data
	signal dispatcher_internal_response_source_ready                    : std_logic;                      -- prefetcher_internal:st_snk_ready -> dispatcher_internal:src_response_ready
	signal dispatcher_internal_write_command_source_valid               : std_logic;                      -- dispatcher_internal:src_write_master_valid -> write_mstr_internal:snk_command_valid
	signal dispatcher_internal_write_command_source_data                : std_logic_vector(255 downto 0); -- dispatcher_internal:src_write_master_data -> write_mstr_internal:snk_command_data
	signal dispatcher_internal_write_command_source_ready               : std_logic;                      -- write_mstr_internal:snk_command_ready -> dispatcher_internal:src_write_master_ready
	signal write_mstr_internal_response_source_valid                    : std_logic;                      -- write_mstr_internal:src_response_valid -> dispatcher_internal:snk_write_master_valid
	signal write_mstr_internal_response_source_data                     : std_logic_vector(255 downto 0); -- write_mstr_internal:src_response_data -> dispatcher_internal:snk_write_master_data
	signal write_mstr_internal_response_source_ready                    : std_logic;                      -- dispatcher_internal:snk_write_master_ready -> write_mstr_internal:src_response_ready
	signal reset_n_reset_n_ports_inv                                    : std_logic;                      -- reset_n_reset_n:inv -> [dispatcher_internal:reset, prefetcher_internal:reset, write_mstr_internal:reset]

begin

	dispatcher_internal : component dispatcher
		generic map (
			MODE                        => 2,
			RESPONSE_PORT               => 1,
			DESCRIPTOR_INTERFACE        => 1,
			DESCRIPTOR_FIFO_DEPTH       => 128,
			ENHANCED_FEATURES           => 0,
			DESCRIPTOR_WIDTH            => 128,
			DESCRIPTOR_BYTEENABLE_WIDTH => 16
		)
		port map (
			clk                     => clock_clk,                                                                                                                                                                                                                                                          --                clock.clk
			reset                   => reset_n_reset_n_ports_inv,                                                                                                                                                                                                                                          --          clock_reset.reset
			csr_writedata           => csr_writedata,                                                                                                                                                                                                                                                      --                  CSR.writedata
			csr_write               => csr_write,                                                                                                                                                                                                                                                          --                     .write
			csr_byteenable          => csr_byteenable,                                                                                                                                                                                                                                                     --                     .byteenable
			csr_readdata            => csr_readdata,                                                                                                                                                                                                                                                       --                     .readdata
			csr_read                => csr_read,                                                                                                                                                                                                                                                           --                     .read
			csr_address             => csr_address,                                                                                                                                                                                                                                                        --                     .address
			src_response_data       => dispatcher_internal_response_source_data,                                                                                                                                                                                                                           --      Response_Source.data
			src_response_valid      => dispatcher_internal_response_source_valid,                                                                                                                                                                                                                          --                     .valid
			src_response_ready      => dispatcher_internal_response_source_ready,                                                                                                                                                                                                                          --                     .ready
			snk_descriptor_data     => prefetcher_internal_descriptor_write_dispatcher_source_data,                                                                                                                                                                                                        --      Descriptor_Sink.data
			snk_descriptor_valid    => prefetcher_internal_descriptor_write_dispatcher_source_valid,                                                                                                                                                                                                       --                     .valid
			snk_descriptor_ready    => prefetcher_internal_descriptor_write_dispatcher_source_ready,                                                                                                                                                                                                       --                     .ready
			src_write_master_data   => dispatcher_internal_write_command_source_data,                                                                                                                                                                                                                      -- Write_Command_Source.data
			src_write_master_valid  => dispatcher_internal_write_command_source_valid,                                                                                                                                                                                                                     --                     .valid
			src_write_master_ready  => dispatcher_internal_write_command_source_ready,                                                                                                                                                                                                                     --                     .ready
			snk_write_master_data   => write_mstr_internal_response_source_data,                                                                                                                                                                                                                           --  Write_Response_Sink.data
			snk_write_master_valid  => write_mstr_internal_response_source_valid,                                                                                                                                                                                                                          --                     .valid
			snk_write_master_ready  => write_mstr_internal_response_source_ready,                                                                                                                                                                                                                          --                     .ready
			descriptor_write        => '0',                                                                                                                                                                                                                                                                --          (terminated)
			descriptor_waitrequest  => open,                                                                                                                                                                                                                                                               --          (terminated)
			descriptor_writedata    => "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",                                                                                                                                 --          (terminated)
			descriptor_byteenable   => "0000000000000000",                                                                                                                                                                                                                                                 --          (terminated)
			mm_response_waitrequest => open,                                                                                                                                                                                                                                                               --          (terminated)
			mm_response_byteenable  => "0000",                                                                                                                                                                                                                                                             --          (terminated)
			mm_response_address     => '0',                                                                                                                                                                                                                                                                --          (terminated)
			mm_response_readdata    => open,                                                                                                                                                                                                                                                               --          (terminated)
			mm_response_read        => '0',                                                                                                                                                                                                                                                                --          (terminated)
			src_read_master_data    => open,                                                                                                                                                                                                                                                               --          (terminated)
			src_read_master_valid   => open,                                                                                                                                                                                                                                                               --          (terminated)
			src_read_master_ready   => '0',                                                                                                                                                                                                                                                                --          (terminated)
			snk_read_master_data    => "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", --          (terminated)
			snk_read_master_valid   => '0',                                                                                                                                                                                                                                                                --          (terminated)
			snk_read_master_ready   => open,                                                                                                                                                                                                                                                               --          (terminated)
			csr_irq                 => open                                                                                                                                                                                                                                                                --          (terminated)
		);

	prefetcher_internal : component altera_msgdma_prefetcher
		generic map (
			ENHANCED_FEATURES          => 0,
			ENABLE_READ_BURST          => 0,
			MAX_READ_BURST_COUNT       => 1,
			MAX_READ_BURST_COUNT_WIDTH => 1,
			DATA_WIDTH                 => 32,
			DATA_BYTEENABLE_WIDTH      => 4,
			DESCRIPTOR_WIDTH           => 128,
			ADDRESS_WIDTH              => 15,
			RESPONSE_FIFO_DEPTH        => 256,
			RESPONSE_FIFO_DEPTH_LOG2   => 8
		)
		port map (
			clk                         => clock_clk,                                                    --                              Clock.clk
			reset                       => reset_n_reset_n_ports_inv,                                    --                        Clock_reset.reset
			mm_read_address             => descriptor_read_master_address,                               --             Descriptor_Read_Master.address
			mm_read_read                => descriptor_read_master_read,                                  --                                   .read
			mm_read_readdata            => descriptor_read_master_readdata,                              --                                   .readdata
			mm_read_waitrequest         => descriptor_read_master_waitrequest,                           --                                   .waitrequest
			mm_read_readdatavalid       => descriptor_read_master_readdatavalid,                         --                                   .readdatavalid
			mm_write_address            => descriptor_write_master_address,                              --            Descriptor_Write_Master.address
			mm_write_write              => descriptor_write_master_write,                                --                                   .write
			mm_write_byteenable         => descriptor_write_master_byteenable,                           --                                   .byteenable
			mm_write_writedata          => descriptor_write_master_writedata,                            --                                   .writedata
			mm_write_waitrequest        => descriptor_write_master_waitrequest,                          --                                   .waitrequest
			mm_write_response           => descriptor_write_master_response,                             --                                   .response
			mm_write_writeresponsevalid => descriptor_write_master_writeresponsevalid,                   --                                   .writeresponsevalid
			st_src_descr_data           => prefetcher_internal_descriptor_write_dispatcher_source_data,  -- Descriptor_Write_Dispatcher_Source.data
			st_src_descr_valid          => prefetcher_internal_descriptor_write_dispatcher_source_valid, --                                   .valid
			st_src_descr_ready          => prefetcher_internal_descriptor_write_dispatcher_source_ready, --                                   .ready
			st_snk_data                 => dispatcher_internal_response_source_data,                     --                      Response_Sink.data
			st_snk_valid                => dispatcher_internal_response_source_valid,                    --                                   .valid
			st_snk_ready                => dispatcher_internal_response_source_ready,                    --                                   .ready
			mm_csr_address              => prefetcher_csr_address,                                       --                                Csr.address
			mm_csr_read                 => prefetcher_csr_read,                                          --                                   .read
			mm_csr_write                => prefetcher_csr_write,                                         --                                   .write
			mm_csr_writedata            => prefetcher_csr_writedata,                                     --                                   .writedata
			mm_csr_readdata             => prefetcher_csr_readdata,                                      --                                   .readdata
			csr_irq                     => csr_irq_irq,                                                  --                            Csr_Irq.irq
			mm_read_burstcount          => open                                                          --                        (terminated)
		);

	write_mstr_internal : component write_master
		generic map (
			DATA_WIDTH                     => 32,
			LENGTH_WIDTH                   => 20,
			FIFO_DEPTH                     => 64,
			STRIDE_ENABLE                  => 0,
			BURST_ENABLE                   => 0,
			PACKET_ENABLE                  => 1,
			ERROR_ENABLE                   => 1,
			ERROR_WIDTH                    => 6,
			BYTE_ENABLE_WIDTH              => 4,
			BYTE_ENABLE_WIDTH_LOG2         => 2,
			ADDRESS_WIDTH                  => 27,
			FIFO_DEPTH_LOG2                => 6,
			SYMBOL_WIDTH                   => 8,
			NUMBER_OF_SYMBOLS              => 4,
			NUMBER_OF_SYMBOLS_LOG2         => 2,
			MAX_BURST_COUNT_WIDTH          => 1,
			UNALIGNED_ACCESSES_ENABLE      => 0,
			ONLY_FULL_ACCESS_ENABLE        => 0,
			BURST_WRAPPING_SUPPORT         => 0,
			PROGRAMMABLE_BURST_ENABLE      => 0,
			MAX_BURST_COUNT                => 1,
			FIFO_SPEED_OPTIMIZATION        => 1,
			STRIDE_WIDTH                   => 1,
			ACTUAL_BYTES_TRANSFERRED_WIDTH => 21
		)
		port map (
			clk                => clock_clk,                                      --             Clock.clk
			reset              => reset_n_reset_n_ports_inv,                      --       Clock_reset.reset
			master_address     => mm_write_address,                               -- Data_Write_Master.address
			master_write       => mm_write_write,                                 --                  .write
			master_byteenable  => mm_write_byteenable,                            --                  .byteenable
			master_writedata   => mm_write_writedata,                             --                  .writedata
			master_waitrequest => mm_write_waitrequest,                           --                  .waitrequest
			snk_data           => st_sink_data,                                   --         Data_Sink.data
			snk_valid          => st_sink_valid,                                  --                  .valid
			snk_ready          => st_sink_ready,                                  --                  .ready
			snk_sop            => st_sink_startofpacket,                          --                  .startofpacket
			snk_eop            => st_sink_endofpacket,                            --                  .endofpacket
			snk_empty          => st_sink_empty,                                  --                  .empty
			snk_error          => st_sink_error,                                  --                  .error
			snk_command_data   => dispatcher_internal_write_command_source_data,  --      Command_Sink.data
			snk_command_valid  => dispatcher_internal_write_command_source_valid, --                  .valid
			snk_command_ready  => dispatcher_internal_write_command_source_ready, --                  .ready
			src_response_data  => write_mstr_internal_response_source_data,       --   Response_Source.data
			src_response_valid => write_mstr_internal_response_source_valid,      --                  .valid
			src_response_ready => write_mstr_internal_response_source_ready,      --                  .ready
			master_burstcount  => open                                            --       (terminated)
		);

	reset_n_reset_n_ports_inv <= not reset_n_reset_n;

end architecture rtl; -- of q_sys_msgdma_rx
